def generate_search_queries(location, topic):
    templates = [
        'site:instagram.com "{topic}" "{location}"',
        'site:instagram.com "best {topic}" accounts in "{location}"',
        'site:instagram.com "top {topic}" profiles {location}',
        'site:instagram.com accounts about {topic} near "{location}"',
        'site:instagram.com "{location}" "{topic}"',
        'site:instagram.com "popular {topic}" pages in "{location}"',
        'site:instagram.com "{location} {topic}" influencers',
        'site:instagram.com "{topic} lovers" accounts "{location}"',
        'site:instagram.com "must follow {topic}" profiles in "{location}"',
        'site:instagram.com "{topic} photography" accounts "{location}"',
        'site:instagram.com "{location}" accounts for {topic}',
        'site:instagram.com "{topic} community" profiles "{location}"',
        'site:instagram.com "{topic}" "{location}" followers',
        'site:instagram.com "{topic}" "{location}" -reels -stories',
        'site:instagram.com "{location}" "{topic}" -explore',
        'site:instagram.com "{topic}" "{location}" official',
        'site:instagram.com "{location}" "{topic}" page',
        'site:instagram.com "real {topic}" accounts "{location}"',
        'site:instagram.com "active {topic}" profiles "{location}"',
        'site:instagram.com "instagram {topic}" "{location}"',
        'site:instagram.com "verified {topic}" accounts "{location}"',
        'site:instagram.com "best rated {topic}" accounts in "{location}"',
        'site:instagram.com "local {topic}" instagram "{location}"',
        'site:instagram.com "{topic} influencer" in "{location}"',
        'site:instagram.com "{location}" "{topic}" blogger',
        'site:instagram.com "{topic}" "{location}" posts',
        'site:instagram.com "top rated {topic}" profiles "{location}"',
        'site:instagram.com "{topic}" instagrammers in "{location}"',
        'site:instagram.com "trending {topic}" accounts "{location}"',
        'site:instagram.com "{location}" "{topic}" stars',
        'site:instagram.com "{topic}" "{location}" artists',
        'site:instagram.com "{location}" {topic} "page"',
        'site:instagram.com "{topic}" "{location}" fanpage',
        'site:instagram.com "popular {topic}" "{location}" accounts',
        'site:instagram.com "{location}" "{topic}" photographers',
        'site:instagram.com "creative {topic}" accounts "{location}"',
        'site:instagram.com "{topic}" "{location}" enthusiasts',
        'site:instagram.com "best {topic}" profiles "{location}"',
        'site:instagram.com "{topic}" in "{location}" community',
        'site:instagram.com "{location}" "{topic}" fan club',
        'site:instagram.com "expert {topic}" accounts "{location}"',
        'site:instagram.com "{topic}" "{location}" daily posts',
        'site:instagram.com "top {topic}" "{location}" pages',
        'site:instagram.com "featured {topic}" accounts "{location}"',
        'site:instagram.com "{location}" "{topic}" groups',
        'site:instagram.com "{topic}" "{location}" reviews',
        'site:instagram.com "best {topic}" "{location}" influencers',
        'site:instagram.com "{location}" "{topic}" content creators',
        'site:instagram.com "{topic}" "{location}" photographers',
    ]

    return templates

